# Generated by Django 3.0.5 on 2020-06-16 19:48

from django.conf import settings
import django.contrib.auth.models
import django.core.exceptions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', django.core.exceptions.PermissionDenied),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
